import { mysqlEnum, mysqlTable, timestamp, varchar } from "drizzle-orm/mysql-core";

/**
 * An independently identifiable Discord bot runtime worker (docs/adr/0011).
 * PK is an operator-assigned stable string ("worker-us-east-1a"), provisioned
 * at deploy time — not autogenerated on first contact, per ADR-0011's
 * "independent worker IDs" requirement.
 *
 * `bootstrapSecretHash`/`bootstrapSecretSalt` store a one-way hash of the
 * worker's bootstrap secret (Node's built-in `crypto.scrypt`, fixed cost
 * parameters — see apps/api/src/lib/worker-identity.ts). The plaintext
 * secret is never stored anywhere, ever.
 *
 * This is a single-secret design: it does not model "old + new valid during
 * a cutover window" (ADR-0011's rotation ideal). Rotation in Phase 3 simply
 * overwrites the hash, with no dual-validity window — an accepted Phase 3
 * floor, the same deliberate-scaffolding treatment already given to
 * bot-credentials.ts. Full dual-secret cutover support is future work.
 *
 * `status` supports individual revocation (ADR-0011) independent of every
 * other worker's credentials.
 */
export const workers = mysqlTable("workers", {
  id: varchar("id", { length: 64 }).primaryKey(),
  bootstrapSecretHash: varchar("bootstrap_secret_hash", { length: 255 }).notNull(),
  bootstrapSecretSalt: varchar("bootstrap_secret_salt", { length: 64 }).notNull(),
  status: mysqlEnum("status", ["ACTIVE", "REVOKED"]).notNull().default("ACTIVE"),
  lastSeenAt: timestamp("last_seen_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow().onUpdateNow(),
});
